title: "Kirtunia Rahul"
description: "Composite Structural Engineer | FEA | Advanced Manufacturing"
url: "https://kirtuniarahul.github.io"
baseurl: ""

theme: jekyll-theme-midnight

author:
  name: "Kirtunia Rahul"
  email: "kirtunia_rahul1@alumni.baylor.edu"

social:
  github: "https://github.com/kirtuniarahul"
  linkedin: "https://www.linkedin.com/in/kirtunia-rahul"

markdown: kramdown
permalink: pretty
