title: "Kirtunia Rahul"
description: "Composite Structural Engineer | FEA | Advanced Manufacturing"
url: "https://kirtuniarahul.github.io"
baseurl: ""
theme: jekyll-theme-cayman
author:
  name: "Kirtunia Rahul"
  email: "kirtunia_rahul1@alumni.baylor.edu"
github_username: "kirtuniarahul"
linkedin_url: "https://www.linkedin.com/in/kirtunia-rahul"
show_downloads: false
